
imagePullSecrets:
  - name: "pull-secret"

ingress:
  enabled: true
  hosts:
    - host: "rsp.lapp.in2p3.fr"
      paths: ["/moneypenny"]
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://rsp.lapp.in2p3.fr/auth?scope=admin:provision"

orders:
  commission:
    - name: initcommission
      image: lsstsqre/inituserhome
      securityContext:
        runAsUser: 0
        runAsNonRootUser: false
      volumeMounts:
      - mountPath: /homedirs
        name: homedirs
  volumes:
    - name: homedirs
      nfs:
        server: 134.158.100.202
        path: /data/nfsdir/jhome


pull-secret:
  enabled: true
  path: "secret/k8s_operator/rsp-lapp/pull-secret"
