cadc-tap:
  pull_secret: 'pull-secret'
  use_mock_qserv: true

  host: "rsp.lapp.in2p3.fr"

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: 'secret/k8s_operator/rsp-lapp/tap'

  ingress:
    authenticated_annotations:
      nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Uid, X-Auth-Request-Token
      nginx.ingress.kubernetes.io/auth-url: "https://rsp.lapp.in2p3.fr/auth?scope=read:tap&auth_type=basic&delegate_to=tap"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        auth_request_set $auth_token $upstream_http_x_auth_request_token;
        proxy_set_header Authorization "Bearer $auth_token";

#  gcs_bucket: 'async-results.lsst.codes'
#  gcs_bucket_url: 'http://async-results.lsst.codes'

pull-secret:
  enabled: true
  path: secret/k8s_operator/rsp-lapp/pull-secret

