environment: minikube
fqdn: minikube.lsst.codes
vault_path_prefix: secret/k8s_operator/minikube.lsst.codes

alert_stream_broker:
  enabled: false
cachemachine:
  enabled: false
cert_issuer:
  enabled: false
cert_manager:
  enabled: false
datalinker:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
mobu:
  enabled: false
moneypenny:
  enabled: false
ingress_nginx:
  enabled: false
noteburst:
  enabled: false
nublado2:
  enabled: false
obstap:
  enabled: false
plot_navigator:
  enabled: false
portal:
  enabled: false
postgres:
  enabled: true
sasquatch:
  enabled: true
semaphore:
  enabled: false
sherlock:
  enabled: false
squareone:
  enabled: false
squash_api:
  enabled: false
strimzi:
  enabled: true
strimzi_registry_operator:
  enabled: false
tap:
  enabled: false
tap_schema:
  enabled: false
vault_secrets_operator:
  enabled: true
vo_cutouts:
  enabled: false
