environment: rsp-lapp
fqdn: rsp.lapp.in2p3.fr
vault_path_prefix: secret/k8s_operator/rsp-lapp

alert_stream_broker:
  enabled: false
argo:
  enabled: true
cachemachine:
  enabled: true
cert_issuer:
  enabled: false
cert_manager:
  enabled: true
chronograf:
  enabled: false
datalinker:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
mobu:
  enabled: false
moneypenny:
  enabled: true
ingress_nginx:
  enabled: true
noteburst:
  enabled: false
nublado2:
  enabled: true
obstap:
  enabled: false
plot_navigator:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
rancher_external_ip_webhook:
  enabled: false
semaphore:
  enabled: false
squareone:
  enabled: true
squash_api:
  enabled: false
strimzi:
  enabled: false
strimzi_registry_operator:
  enabled: false
tap:
  enabled: true
tap_schema:
  enabled: true
vault_secrets_operator:
  enabled: true
vo_cutouts:
  enabled: false


