environment: rsp-lapp
fqdn: rsp.lapp.in2p3.fr
vault_path_prefix: secret/k8s_operator/rsp-lapp

alert_stream_broker:
  enabled: false
cachemachine:
  enabled: true
cert_manager:
  enabled: true
datalinker:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
mobu:
  enabled: false
moneypenny:
  enabled: true
ingress_nginx:
  enabled: true
narrativelog:
  enabled: false
noteburst:
  enabled: false
nublado2:
  enabled: true
obstap:
  enabled: false
plot_navigator:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
sasquatch:
  enable: false
production_tools:
  enable: false
semaphore:
  enabled: false
sherlock:
  enable: false
squareone:
  enabled: true
squash_api:
  enabled: false
strimzi:
  enabled: false
strimzi_registry_operator:
  enabled: false
tap:
  enabled: true
tap_schema:
  enabled: true
vault_secrets_operator:
  enabled: true
vo_cutouts:
  enabled: false


