gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: dboutigny.freeboxos.fr
  vaultSecretsPath: "secret/k8s_operator/dboutigny.freeboxos.fr/gafaelfawr"

  # Reset token storage on every Redis restart.
  redis:
    persistence:
      enabled: false

  config:
    host: "dboutigny.freeboxos.fr"
    databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

    github:
      clientId: "59331e15cb2a3c3261ad"

    # Allow access by GitHub team.
    groupMapping:
      "exec:admin":
        - "lsst-france-calcul"
      "exec:user":
        - "lsst-france-calcul"
        - "lsst-france-invited"
      "read:workspace":
        - "lsst-france-calcul"
        - "lsst-france-invited"
      "read:workspace/user":
        - "lsst-france-calcul"
        - "lsst-france-invited"
      "write:workspace/user":
        - "lsst-france-calcul"
        - "lsst-france-invited"
      "exec:portal":
        - "lsst-france-calcul"
        - "lsst-france-invited"
      "exec:notebook":
        - "lsst-france-calcul"
        - "lsst-france-invited"
      "read:tap":
        - "lsst-france-calcul"
        - "lsst-france-invited"
      "read:image":
        - "lsst-france-calcul"
        - "lsst-france-invited"

    initialAdmins:
       - "hellebore74"
       - "boutigny"

  # Use CILogon authentication.
  #cilogon:
  #  client_id: "cilogon:/client_id/74e865cd71a3a327096d36081166b739"
  #  redirect_url: "https://rsp-lapp.ddns.net/login"
  # login_params:
  #    skin: "LSST"

pull-secret:
  enabled: true
  path: secret/k8s_operator/dboutigny.freeboxos.fr/pull-secret
