# Use the CSI storage class so that we can use snapshots.
redis:
  persistence:
    storageClass: "standard-rwo"

config:
  slackAlerts: true

  github:
    clientId: "0c4cc7eaffc0f89b9ace"

  # Support OpenID Connect clients like Chronograf.
  oidcServer:
    enabled: true

  # Allow access by GitHub team.
  groupMapping:
    "admin:provision":
      - github:
          organization: "lsst-sqre"
          team: "square"
    "exec:admin":
      - github:
          organization: "lsst-sqre"
          team: "square"
      - github:
          organization: "lsst-sqre"
          team: "friends"
    "exec:notebook":
      - github:
          organization: "lsst"
          team: "ops"
      - github:
          organization: "lsst"
          team: "ops-panda"
      - github:
          organization: "lsst-sqre"
          team: "square"
      - github:
          organization: "lsst-sqre"
          team: "friends"
    "exec:portal":
      - github:
          organization: "lsst"
          team: "ops"
      - github:
          organization: "lsst"
          team: "ops-panda"
      - github:
          organization: "lsst-sqre"
          team: "square"
      - github:
          organization: "lsst-sqre"
          team: "friends"
    "read:alertdb":
      - github:
          organization: "lsst-sqre"
          team: "square"
      - github:
          organization: "lsst-sqre"
          team: "friends"
    "read:image":
      - github:
          organization: "lsst"
          team: "ops"
      - github:
          organization: "lsst"
          team: "ops-panda"
      - github:
          organization: "lsst-sqre"
          team: "square"
      - github:
          organization: "lsst-sqre"
          team: "friends"
    "read:tap":
      - github:
          organization: "lsst"
          team: "ops"
      - github:
          organization: "lsst"
          team: "ops-panda"
      - github:
          organization: "lsst-sqre"
          team: "square"
      - github:
          organization: "lsst-sqre"
          team: "friends"

  initialAdmins:
    - "afausti"
    - "athornton"
    - "cbanek"
    - "frossie"
    - "jonathansick"
    - "rra"
    - "simonkrughoff"

  errorFooter: |
    To report problems or ask for help, please open an issue in the
    <a href="https://github.com/rubin-dp0/Support/issues">GitHub
    rubin-dp0/Support project</a>.

cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-int-dc5d:us-central1:science-platform-int-8f439af2"
  serviceAccount: "gafaelfawr@science-platform-int-dc5d.iam.gserviceaccount.com"
