strimzi-kafka: {}

influxdb:
  ingress:
    enabled: true
    hostname: data-dev.lsst.cloud

chronograf:
  ingress:
    enabled: true
    hostname: data-dev.lsst.cloud

  env:
    GENERIC_NAME: "CILogon"
    GENERIC_AUTH_URL: https://data-dev.lsst.cloud/auth/openid/login
    GENERIC_TOKEN_URL: https://data-dev.lsst.cloud/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://data-dev.lsst.cloud/.well-known/jwks.json
    GENERIC_API_URL: https://data-dev.lsst.cloud/auth/userinfo
    GENERIC_SCOPES: openid
    PUBLIC_URL: https://data-dev.lsst.cloud/
    STATUS_FEED_URL: "https://lsst-sqre.github.io/sasquatch/feeds/idfdev.json"

vaultSecretsPath: secret/k8s_operator/data-dev.lsst.cloud

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-dev.lsst.cloud/pull-secret
