apiVersion: v1
kind: Service
metadata:
  name: plot-navigator
  labels:
    {{- include "plot-navigator.labels" . | nindent 4 }}
spec:
  selector:
    app: plot-navigator
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
