apiVersion: v2
name: times-square
version: 1.0.0
description: |
  An API service for managing and rendering parameterized Jupyter notebooks.
home: https://github.com/lsst-sqre/times-square
type: application

# The default version tag of the times-square docker image
appVersion: 0.4.0b1

dependencies:
  - name: redis
    version: 16.9.10
    repository: https://charts.bitnami.com/bitnami
