ingress-nginx:
  controller:
    config:
      compute-full-forwarded-for: "true"
      large-client-header-buffers: "4 64k"
      proxy-body-size: "100m"
      proxy-buffer-size: "64k"
      ssl-redirect: "true"
      use-forwarded-headers: "true"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    service:
      externalTrafficPolicy: Local
      externalIPs:
        - 134.158.100.201
      type: NodePort
    admissionWebhooks:
        enabled: false 
  
    extraArgs:
      default-ssl-certificate: ingress-nginx/ingress-certificate
    podLabels:
      hub.jupyter.org/network-access-proxy-http: "true"

vault_certificate:
  enabled: true
  path: secret/k8s_operator/rsp-lapp/ingress-nginx

pull-secret:
  enabled: true
  path: secret/k8s_operator/rsp-lapp/pull-secret

