ingress-nginx:
  controller:
    config:
      compute-full-forwarded-for: "true"
      large-client-header-buffers: "4 64k"
      proxy-body-size: "100m"
      proxy-buffer-size: "64k"
      ssl-redirect: "true"
      use-forwarded-headers: "true"
      proxy-connect-timeout: "180"
      proxy-read-timeout: "180"
      proxy-send-timeout: "180"
    service:
      externalTrafficPolicy: Local
      externalIPs:
        - 134.158.100.201
      type: NodePort
    admissionWebhooks:
        enabled: false 
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1

    extraArgs:
      default-ssl-certificate: ingress-nginx/ingress-certificate
    podLabels:
      hub.jupyter.org/network-access-proxy-http: "true"

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "180"

vault_certificate:
  enabled: true
  path: secret/k8s_operator/rsp-lapp/ingress-nginx

pull-secret:
  enabled: true
  path: secret/k8s_operator/rsp-lapp/pull-secret

