noteburst:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: "rsp.lapp.in2p3.fr"
        paths:
          - path: "/noteburst"
            pathType: Prefix
  imagePullSecrets:
    - name: "pull-secret"
  vaultSecretsPath: "secret/k8s_operator/rsp-lapp/noteburst"

pull-secret:
  enabled: true
  path: secret/k8s_operator/rsp-lapp/pull-secret
