
imagePullSecrets:
  - name: "cachemachine-secret"

ingress:
  enabled: true
  host: "rsp.lapp.in2p3.fr"

autostart:
  jupyter: |
    {
      "name": "jupyter",
      "labels": {},
      "repomen": [
        {
          "type": "RubinRepoMan",
          "registry_url": "registry.hub.docker.com",
          "repo": "lsstsqre/sciplat-lab",
          "recommended_tag": "recommended",
          "num_releases": 1,
          "num_weeklies": 2,
          "num_dailies": 3	    
        }
#	,
#        {
#          "type": "SimpleRepoMan",
#          "images": [
#            {
#              "image_url": "hub.docker.com/repository/docker/hellebore74/jupyterlab:w_2022_01_cta_v0.2",
#              "name": "Test_CTA"
#            }
#          ]
#        }
      ]
    }
    

