autostart:
  jupyter: |
    {
      "name": "jupyter",
      "labels": {},
      "repomen": [
        {
          "type": "RubinRepoMan",
          "registry_url": "ts-dockerhub.lsst.org",
          "repo": "sal-sciplat-lab",
          "recommended_tag": "recommended_c0027",
          "num_releases": 0,
          "num_weeklies": 3,
          "num_dailies": 2,
          "cycle": 27,
          "alias_tags": [
              "latest",
              "latest_daily",
              "latest_weekly"
          ]
        }
      ]
    }
