
imagePullSecrets:
  - name: "cachemachine-secret"

ingress:
  enabled: true
  host: "rsp.lapp.in2p3.fr"

autostart:
  jupyter: |
    {
      "name": "jupyter",
      "labels": {},
      "repomen": [
        {
          "type": "RubinRepoMan",
          "registry_url": "docker.io",
          "repo": "hellebore74/jupyterlab",
          "recommended_tag": "recommended",
          "num_releases": 1,
          "num_weeklies": 2,
          "num_dailies": 3	    
        }
      ]
    }
    

