
cachemachine:
  imagePullSecrets:
    - name: "cachemachine-secret"

  ingress:
    enabled: true
    host: "rsp.lapp.in2p3.fr"

  vaultSecretsPath: "secret/k8s_operator/rsp-lapp/pull-secret"

  autostart:
    jupyter: |
      {
        "name": "jupyter",
        "labels": {},
        "repomen": [
          {
            "type": "RubinRepoMan",
            "registry_url": "registry.hub.docker.com",
            "repo": "hellebore74/jupyterlab",
            "recommended_tag": "recommended",
            "num_releases": 1,
            "num_weeklies": 2,
            "num_dailies": 3
          }
          {
            "type": "RubinRepoMan",
            "registry_url": "registry.hub.docker.com",
            "repo": "lsstsqre/sciplat-lab",
            "recommended_tag": "recommended",
            "num_releases": 1,
            "num_weeklies": 2,
            "num_dailies": 3
          }
        ]
      }



