# Default values for datalinker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of web deployment pods to start
replicaCount: 1

image:
  # -- Image to use in the datalinker deployment
  repository: lsstsqre/datalinker

  # -- Pull policy for the datalinker image
  pullPolicy: Always

  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

# -- Annotations for the datalinker deployment pod
podAnnotations: {}

service:
  # -- Type of service to create
  type: ClusterIP

  # -- Port of the service to create and map to the ingress
  port: 8080

ingress:
  # -- Create an ingress resource
  enabled: true

  # -- Gafaelfawr auth query string (default, unauthenticated)
  gafaelfawrAuthQuery: ""

  # -- Additional annotations for the ingress rule
  annotations: {}

  # -- Path type for the ingress rule
  pathType: ImplementationSpecific

  # -- URL path to dispatch to the datalinker deployment pod
  path: "/api/datalink"

  # -- Ingress class
  className: nginx

# -- Resource limits and requests for the datalinker deployment pod
resources: {}

autoscaling:
  # -- Enable autoscaling of datalinker deployment
  enabled: false

  # -- Minimum number of datalinker deployment pods
  minReplicas: 1

  # -- Maximum number of datalinker deployment pods
  maxReplicas: 100

  # -- Target CPU utilization of datalinker deployment pods
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Node selection rules for the datalinker deployment pod
nodeSelector: {}

# -- Tolerations for the datalinker deployment pod
tolerations: []

# -- Affinity rules for the datalinker deployment pod
affinity: {}

# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
global:
  # -- Base URL for the environment
  # @default -- Set by Argo CD
  baseUrl: ""

  # -- Host name for ingress
  # @default -- Set by Argo CD
  host: ""

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""
